# Generated by Django 4.1.7 on 2023-08-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='new',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
