# Generated by Django 4.1.7 on 2023-08-08 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('to', '0002_todo_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='use',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
